apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app-2
  template:
    metadata:
      labels:
        app: demo-app-2
    spec:
      containers:
        - name: demo-app-2
          image: 992382508838.dkr.ecr.us-east-1.amazonaws.com/demo-app:app1-latest
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: "$(DB_HOST)"
            - name: DB_USER
              value: "$(DB_USER)"
            - name: DB_PASSWORD
              value: "$(DB_PASSWORD)"
            - name: DB_NAME
              value: "$(DB_NAME)"
